wordpress:
  build: .
  links:
    - db:mysql
  ports:
    - 8080:80
  volumes:
    - ./_html:/var/www/html
    - ./bin:/var/www/html/bin

db:
  image: mysql
  ports:
    - 3306:3306
  environment:
    MYSQL_ROOT_PASSWORD: This1sP@55w0rd
